apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: logoutput-container
          image: YOUR_IMAGE_HERE
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE
          volumeMounts:
            - name: info-volume
              mountPath: /etc/config
      volumes:
        - name: info-volume
          configMap:
            name: logoutput-config
            items:
              - key: information.txt
                path: information.txt
