apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
      - name: project-container
        image: YOUR_PROJECT_IMAGE
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"  # can also pass as env variable in cluster
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: project-config
                key: BACKEND_URL
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: project-config
                key: WELCOME_MESSAGE
