metadata:
  name: log-output
  namespace: exercises

apiVersion: v1
kind: Service
metadata:
  name: logoutput-svc
  namespace: project

spec:
  selector:
    app: log-output
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
