apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-v1
  labels:
    app: greeter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter
      version: v1
  template:
    metadata:
      labels:
        app: greeter
        version: v1
    spec:
      containers:
        - name: greeter
          image: hashicorp/http-echo
          args:
            - "-text=hello from v1"
          ports:
            - containerPort: 5678
