apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-1
spec:
  selector:
    app: greeter
    version: v1
  ports:
    - port: 80
      targetPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-2
spec:
  selector:
    app: greeter
    version: v2
  ports:
    - port: 80
      targetPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: greeter
spec:
  selector:
    app: greeter   # all versions
  ports:
    - port: 80
      targetPort: 5678
