apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: greeter-route
spec:
  parentRefs:
    - name: greeter
      kind: Service
  rules:
    - backendRefs:
        - name: greeter-svc-1
          weight: 75
        - name: greeter-svc-2
          weight: 25
