apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pingpong-route
spec:
  parentRefs:
    - name: gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/pingpong"
      filters:
        - type: URLRewrite
          urlRewrite:
            replacePrefixMatch: "/"
      backendRefs:
        - name: pingpong-service
          port: 3000
