apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pingpong-cpu-check
  namespace: <YOUR-NAMESPACE>
spec:
  metrics:
    - name: cpu-usage-rate
      interval: 60s
      count: 5
      successCondition: result < 0.3
      failureCondition: result >= 0.3
      provider:
        prometheus:
          address: http://prometheus-server.prometheus.svc.cluster.local
          query: |
            sum(
              rate(container_cpu_usage_seconds_total{
                namespace="<YOUR-NAMESPACE>",
                container!="POD"
              }[5m])
            )
