metadata:
  name: pingpong
  namespace: exercises

apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: project

spec:
  selector:
    app: pingpong
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
