apiVersion: v1
kind: Service
metadata:
  name: log-output-multi-service
spec:
  selector:
    app: log-output-multi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
