apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo
  namespace: project
spec:
  schedule: "0 * * * *"  # every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-todo
            image: curlimages/curl:7.87.0
            command:
              - /bin/sh
              - -c
              - |
                # Fetch random Wikipedia URL
                URL=$(curl -sI https://en.wikipedia.org/wiki/Special:Random | grep -i Location | awk '{print $2}' | tr -d '\r\n')
                # Post to todo backend
                curl -X POST $TODO_BACKEND_URL/todos -H "Content-Type: application/json" -d "{\"text\": \"Read $URL\"}"
            env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend:3002"  # replace with your backend service URL
          restartPolicy: OnFailure
